In [140]:
import numpy as np 
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder 

In [40]:
df = {'age' :[60,27,42,31,65] , 
      'gender' : ["Male","Male" ,"Male" ,"Female", "Female"] ,
      'fever' : [103.0 ,100.0 ,101.0 ,np.NaN,101.0] , 
      'cough' : ["Mild" ,"Mild" ,"strong" ,"strong" ,"Mild"],
      'city' : ["Kolkata" ,"Delhi" ,"Delhi","Kolkata" ,"Mumbai"] ,
      'has_covid': ["No" ,"Yes" ,"No","No" ,"Yes"]
     }

In [41]:
df= pd.DataFrame(df)

In [42]:
df

age  gender  fever   cough     city has_covid
0   60    Male  103.0    Mild  Kolkata        No
1   27    Male  100.0    Mild    Delhi       Yes
2   42    Male  101.0  strong    Delhi        No
3   31  Female    NaN  strong  Kolkata        No
4   65  Female  101.0    Mild   Mumbai       Yes

In [43]:
x_train = df.iloc[:,0:-1]
x_train

age  gender  fever   cough     city
0   60    Male  103.0    Mild  Kolkata
1   27    Male  100.0    Mild    Delhi
2   42    Male  101.0  strong    Delhi
3   31  Female    NaN  strong  Kolkata
4   65  Female  101.0    Mild   Mumbai

In [44]:
y_train = df[["has_covid"]]
y_train

has_covid
0        No
1       Yes
2        No
3        No
4       Yes

In [48]:
# adding simple imputer to fever column 
si = SimpleImputer() 


In [51]:
x_train_fever = si.fit(x_train[["fever"]]) 
x_train_fever = si.transform(x_train[["fever"]]) 

In [174]:
x_train_fever

array([[103.  ],
       [100.  ],
       [101.  ],
       [101.25],
       [101.  ]])

In [175]:
# ordinal Encoding  -> cough  
oe =  OrdinalEncoder(categories =[["Mild" , "strong"]]) 
x_train_cough = oe.fit_transform(x_train[['cough']]) 
# x_train_cough=  oe.transform(x_train[['cough']])

In [94]:
x_train_cough

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [156]:
ohe = OneHotEncoder(drop="first")

x_train_gender_city =  ohe.fit_transform(x_train[["gender","city"]])
x_train_gender_city


<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [110]:
#extracting age 
x_train_age = x_train.drop(columns =['gender','fever','cough','city']).values

In [146]:
x_train_age

array([[60],
       [27],
       [42],
       [31],
       [65]], dtype=int64)

In [147]:
x_train_transformed =  np.concatenate((x_train_age ,x_train_fever , x_train_gender_city , x_train_cough) , axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [134]:
x_train_transformed

NameError: name 'x_train_transformed' is not defined

# Everything do  with Column transformer 

In [159]:
from sklearn.compose import ColumnTransformer 

In [186]:
transformer  = ColumnTransformer(transformers= [
    ('tnf1' , SimpleImputer() , ["fever"]),
    ('tnf2' ,OrdinalEncoder(categories=["Mild","strong"]) , ['cough']),
    ('tnf3' , OneHotEncoder(drop ="first") ,["gender" ,"city"] )
] , remainder ='passthrough' ) 
#  remainder  = drop hoite pare 

In [187]:
transformer.fit_transform(x_train)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

age  gender  fever   cough     city
0   60    Male  103.0    Mild  Kolkata
1   27    Male  100.0    Mild    Delhi
2   42    Male  101.0  strong    Delhi
3   31  Female    NaN  strong  Kolkata
4   65  Female  101.0    Mild   Mumbai